spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_ADDRESS}/${DATABASE_NAME}?serverTimezone=UTC
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: ${APPLICATION_PORT}
  servlet:
    encoding:
      force: true
      charset: UTF-8
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace